### ISSUE TITLE
Configure Netlify deployments

### ISSUE THREAD

**Issue by jvendrell** [MarsBased/decidim-vilanova-static-website#1]
We will use [Netlify](https://www.netlify.com/) to deploy the website. Configure a new environment and setup deployments.

**Domain:**

participa.vilanova.cat

**IT contact to configure the domain:**

Òscar Benadí
[obenadi@vilanova.cat](obenadi@vilanova.cat)
93 814 00 00 ext. 1281

**Comment by jvendrell** [comment]
@xredo Vilanova sent us all the info we need to configure deployments and domain.

**Comment by xredo** [comment]
We requested the domain change to Vilanova. Meanwhile we can access the site using the url: decidim-vilanova.netlify.com. I will close the issue once the domain is working.

**Comment by jvendrell** [comment]
The domain is working, so I'm closing the issue.
